### ISSUE TITLE
IBM development is locking down the SED command

### ISSUE THREAD

**Issue by kurtandsandy** [opokam/eezh#1]
Because of the way that it has been used with some root hacks, IBM development is locking down the **sed** command.  
[https://delivery04.dhe.ibm.com/sar/CMA/HMA/09usk/0/MH01895.readme.html](https://delivery04.dhe.ibm.com/sar/CMA/HMA/09usk/0/MH01895.readme.html)   This link is actually down now from the last time I checked it.
"The commands alias and unalias have been removed from restricted shell."

It is recommended to run sed commands off the HMC via ssh if complex processing is needed.
I work in IBM HMC support.

**Comment by opokam** [comment]
Use of sed was removed in v2.3
